services:
  - type: web
    name: AL-MUTAMARRID-TECH-USERBOT
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: API_ID
        sync: false
        placeholder: "أدخل API_ID الخاص بك"
      - key: API_HASH
        sync: false
        placeholder: "أدخل API_HASH الخاص بك"
      - key: SESSION
        sync: false
        placeholder: "أدخل كود الجلسة (String Session)"
      - key: SUDO_USERS
        sync: false
        placeholder: "أدخل ايديك (ID) لكي يتعرف عليك السورس"
      - key: PYTHON_VERSION
        value: 3.10.0
